### ISSUE TITLE
Liquid Issuance Coordination

### ISSUE THREAD

**Issue by GR3G0RYO** [planetmint/planetmint-go#123]
- [x]  PoPResult/Timer(every 2min): an event is triggered RE-ISSUANCE
    - [x]  Block-Proposer von comment BFT requested creation of one Msg IssueRDDLonLiquid
        - [x]  Message contains: unsigned reissuing tx (by a service or by a validator)
    - [x]  part of the cosmos consensus: validators verify the Msg IssueRDDLonLiquid containing the tx and the signature (including the distribution) (in the ante handler)
    - [x]  after the consensus took place and the TX is in a block, the block-Proposer (thus one validator) sends the TX to the liquid network
    - [x]  The proper notarized TXBroadcaseResult in a message to the network.
        - [x]  this is again to be verified before consensus (in the ante handler)
