### ISSUE TITLE
Implement mint address param

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint-go#139]
## Description
Implement a governable param for the MintAddress, which is used to mint PLMNT token. There have been some changes on the Cosmos SDK handling of params which need to be researched before adding more details to this ticket.

## Tasks
- [x] add dao.UpdateParams message
- [x] implement msg handler
- [x] implement dao params store
- [x] update params proto
- [x] adjust e2e mint token test

**Comment by eckelj** [comment]
@LaurentMontBlanc can you elaborate a bit more? what should a meaningful convention look like? what are examples for that?

**Comment by LaurentMontBlanc** [comment]
https://github.com/cosmos/cosmos-sdk/blob/346044afd0ecd4738c13993d2ac75da8e242266d/x/consensus/keeper/keeper.go
