### ISSUE TITLE
Trigger token reissuance on Liquid including the distribution.

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint-go#2]
A planetmint validator (the block proposer of the current block) will start the RDDL issuing process on Liquid.
The process will be triggered every by Pop. 
The PoP will be triggered every 120 seconds, and its result will trigger the issuing process. 

1. Initially, a reissuable token needs to be set up by the watchman. (Tom)
2. The watchman will reissue 1012 RDDL tokens on liquid and distribute 61% to a community escrow account that backs tokens to be minted Planetmint.

## Tasks
- [x] add config for n-epochs until PoP/token issuance to config
- [x] implement check that panics if this config is not set
- [x] add config for RDDL issuance service endpoint 
- [x] implement call to service RDDL issuance service
