### ISSUE TITLE
Mainnet: public accessability

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint-go#316]
- [ ]  ~[Exposer of all mainnet nodes API & RPC](https://github.com/rddl-network/ansible/issues/30)~
- [x]  [Deploy rddl2plmnt service to mainnet](https://github.com/rddl-network/ansible/issues/32) 
- [x] [303](https://github.com/planetmint/planetmint-go/issues/exposed303) definition and common* DAO funding of initial Device interactions (6-12 month if notarization is done once per hour).

- [x] [publish mqtt.rddl.io credentials so that PoP can by the participants](https://github.com/rddl-network/issues/issues/70) 
- [x] sign machineID on the TA with a different curve/SE, verify signed attestMachine msg on planetmint with SE curve

- [x] mainnet & testnet alert manager (prometheus)
- [x] mainnet & testnet uptime monitoring 
- [ ] ~mainnet & testnet log aggregation~

|          Service        | Mainnet                                                  | Change Request                                       | phase 1 | phase 2|
| ---------------- | -------------------------------------------------------- | -------------------------------------------------------- |----------------|-------------|
| API exposure/per node     | api.rddl.io                               |       should be exposed per node [30](https://github.com/rddl-network/ansible/issues/30)                        | |X|
| RPC exposure/per node     | rpc.rddl.io    | should be exposed per node [30](https://github.com/rddl-network/ansible/issues/30)  ||X|
| Trust Anchor Registration     | ta.rddl.io |  2b disabled until final launch  [15](https://github.com/rddl-network/ta_attest/issues/15) |X||
| rddl2plmnt         |             https://r2p.rddl.io/       | 2B disabled & then hardened & published again [294](https://github.com/planetmint/planetmint-go/issues/294) |X |X|
| redeem-service |        | 2B set up & deployed [305](https://github.com/planetmint/planetmint-go/issues/305) Redeem service | |X|
| mqtt                    |          mqtt.rddl.io          | configure nodes & publish credentials  [70](https://github.com/rddl-network/issues/issues/70)| |X|
