### ISSUE TITLE
[Docs] gitbook

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint-go#406]
- [ ] Energy Agent
- [ ] HW components
- [ ] SW components
- [ ] Wallet init/key ceremony/ disaster backup preperation....
- [ ] RDDL attestation & setup
- [ ] Shelly/Tasmota configureation / attach/configure SMDs
- [ ] Discord based knowledge base and help/support center / FAQ
- [ ] preattestet Trustwallet usage
