### ISSUE TITLE
Validator Distribribution (12-15) (only mainnet)

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint-go#408]
- [ ] Cosmo-Visor setup to sync validators
- [ ] decouple coordinators from validators
- [ ] validator rewards via PoP
- [ ] technical validator setup/specs
