### ISSUE TITLE
add capabilities to mint send burn kwh tokens

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint-go#433]
- [ ] add messages to mint/send/burn kwh tokens
- [ ] add ante handler so only machines issue are allowed to send these messages
- [ ] add register for energy consumption/production form (optional)
- [ ] add demo scenario to compose setup (produce/send/burn kwh token)
