### ISSUE TITLE
set non testnet default chain params

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint-go#443]
## Description
Set every modules DefaultParams() to something that works for local testcases but is obviously visible when accidentaly deploying.

Example:
```go
// DefaultParams returns a default set of parameters
func DefaultParams() Params {
        return NewParams(
                "plmnt1dyuhg8ldu3d6nvhrvzzemtc3893dys9v9lvdty", // => "IAMNOTAPLANETMINTADDRESSREPLACEME"
                "plmnt",
                "stagedcrddl",
                "crddl",
                "7add40beb27df701e02ee85089c5bc0021bc813823fedb5f1dcb5debda7f3da9", // => "IAMNOTANASSETIDREPLACEME"
                3600,
                5,
                75,
                "vjTyRN2G42Yq3T5TJBecHj1dF1xdhKF89hKV4HJN3uXxUbaVGVR76hAfVRQqQCovWaEpar7G5qBBprFG", // => "IAMNOTAVALIDLIQUIDADDRESSREPLACEME"
                "vjTyRN2G42Yq3T5TJBecHj1dF1xdhKF89hKV4HJN3uXxUbaVGVR76hAfVRQqQCovWaEpar7G5qBBprFG",
                "vjTyRN2G42Yq3T5TJBecHj1dF1xdhKF89hKV4HJN3uXxUbaVGVR76hAfVRQqQCovWaEpar7G5qBBprFG",
                "vjU8eMzU3JbUWZEpVANt2ePJuPWSPixgjiSj2jDMvkVVQQi2DDnZuBRVX4Ygt5YGBf5zvTWCr1ntdqYH",
                "vjTvXCFSReRsZ7grdsAreRR12KuKpDw8idueQJK9Yh1BYS7ggAqgvCxCgwh13KGK6M52y37HUmvr4GdD",
                2000,
                "plmnt1m5apfematgm7uueazhk482026ert95x2l2dx78",
                200000,
                100000000,
        )
}
```

## Tasks
- [ ] replace dao default params
- [ ] replace machine default params
- [ ] fix eventually broken test cases
