### ISSUE TITLE
remove ValidatorAddress from config

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint-go#447]
## Description
ValidatorAddress should be provided by the Trust Wallet

## Tasks
- [x] replace instances of config.ValidatorAddress with config.GetValidatorAddress()
- [x] add getAddress to lib/trust-wallet
- [x] config.GetValidatorAddress should return either configured value or if possible on from a connected Trust Wallet
