### ISSUE TITLE
CID mechanism

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint-go#8]
## Description
The goal is to have a mechanism that allows the proof of provenance for a given notarized asset (data or signal). This is achieved by storing a 32byte hash arbitrary data, the signature of the asset producing machine and  public key of the asset producing machine.

### Tasks
- [x] create NotarizeAsset msg handler
- [x] check if msg creator is attested machine
- [ ] get shortened URL for attested machine
- [x] store CID hash, Signature and pub key on chain

### Actors
 - machine
 - URL service (connects attested machine to shortened static URL)
