### ISSUE TITLE
RDDL 2 PLMNT funding workflow and definition

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint-go#94]
## Prerequisites
 - liquid RDDL escrow account
 - RDDL<>PLMNT conversion rate monitor
 - liquid watchman
 - planetmint msg handler for token mint

## Description
Implement a watchman that observes blocks on liquid. If the block contains a TX to the RDDL escrow account it should trigger the minting of PLMNT tokens. The liquid TX should contain a planetmint address (beneficiary). Currently we have a fixed conversion rate of 1 RDDL to 100 PLMNT but this is possibly subject to change as the PLMNT price is pegged to the price of 1W of solar power but RDDL not.

## Tasks 
- [x] implement msg handler
- [ ] implement watchman
- [ ] define permissions for watchman
- [ ] define conversion rate monitor
