### ISSUE TITLE
deduplicate msg validations

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint-go#98]
## Description
Some of the validation done by the msg servers have been redone on the `AnteHandler`. The following validations can be removed from the msg servers:

## Tasks
- [x] MachineAttestation is trust anchor found
- [x] MachineAttestation is trust anchor already activated
- [x] NotarizeAsset is asset notarized by machine
